apiVersion: v1
data:
  secretkey: a1BiZlJ5S0o5bFM2Yk9yalpYb05IbjFEQ0ovYjNVL0g2bkd5VTROalVFaTJOYXh4d3QyZkxQS2YvNllGU0hRWgovQWxnNmhycmNMeHNzckxDMHhDNFRXZkVxamU2S2h4ajNYMzIxUmczVlo0eHBBWlRXWXdEY3Z5dTBpTUtjaHBRCi9XUktTam55Sy85NFVYS1NuS1k2bmZTeStPT3dKYWRmY2pnaFlya29LQWs9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
